<h2> Save And Load a Trained Model</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

## Pickle

In [7]:
import pickle

Saving model using pickle.dump

here 'wb' represents write mode

In [8]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

Loading model using pickle.Loading

here 'rb' represents read mode

In [10]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [11]:
mp.coef_

array([135.78767123])

In [12]:
mp.intercept_

180616.43835616432

In [13]:
mp.predict([[5000]])

array([859554.79452055])

## Joblib from sklearn
Joblib works efficiently with large number of numpy arrays used

In [14]:
from sklearn.externals import joblib

Saving model using joblib.dump 

In [15]:
joblib.dump(model, 'model_joblib')

['model_joblib']

Loading model using joblib.load

In [16]:
mj = joblib.load('model_joblib')

In [17]:
mj.coef_

array([135.78767123])

In [18]:
mj.intercept_

180616.43835616432

In [19]:
mj.predict([[5000]])

array([859554.79452055])